# Generated by Django 5.2.7 on 2025-11-05 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="动漫名称")),
                (
                    "cover",
                    models.ImageField(upload_to="anime/covers/", verbose_name="封面图"),
                ),
                ("desc", models.TextField(verbose_name="简介")),
                ("year", models.IntegerField(verbose_name="年份")),
                (
                    "rating",
                    models.IntegerField(
                        default=5, help_text="1-5星", verbose_name="评分"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="如: 已完结、连载中",
                        max_length=50,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
            ],
            options={
                "verbose_name": "动漫",
                "verbose_name_plural": "动漫",
                "db_table": "anime",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="carousel/", verbose_name="轮播图"),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
                ("is_show", models.BooleanField(default=True, verbose_name="是否显示")),
            ],
            options={
                "verbose_name": "轮播图",
                "verbose_name_plural": "轮播图",
                "db_table": "carousel",
                "ordering": ["sort"],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="游戏名称")),
                (
                    "cover",
                    models.ImageField(
                        upload_to="games/covers/", verbose_name="游戏封面"
                    ),
                ),
                ("desc", models.TextField(verbose_name="游戏描述")),
                (
                    "play_time",
                    models.CharField(
                        blank=True,
                        help_text="如: 200小时",
                        max_length=100,
                        verbose_name="游玩时长",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        default=5, help_text="1-5星", verbose_name="评分"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
            ],
            options={
                "verbose_name": "游戏",
                "verbose_name_plural": "游戏",
                "db_table": "games",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="Hobby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "hobby_type",
                    models.CharField(
                        choices=[
                            ("game", "游戏"),
                            ("music", "音乐"),
                            ("anime", "动漫"),
                        ],
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="FontAwesome图标类名，如: fa-gamepad",
                        max_length=50,
                        verbose_name="图标类名",
                    ),
                ),
                ("desc", models.TextField(verbose_name="描述")),
            ],
            options={
                "verbose_name": "爱好分类",
                "verbose_name_plural": "爱好分类",
                "db_table": "hobbies",
            },
        ),
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="歌曲名称")),
                ("artist", models.CharField(max_length=200, verbose_name="艺术家")),
                (
                    "album",
                    models.CharField(blank=True, max_length=200, verbose_name="专辑"),
                ),
                (
                    "cover",
                    models.ImageField(upload_to="music/covers/", verbose_name="封面图"),
                ),
                (
                    "audio_url",
                    models.URLField(
                        help_text="网易云音乐外链或其他音频URL", verbose_name="音频链接"
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        help_text="如: 03:45", max_length=20, verbose_name="时长"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
            ],
            options={
                "verbose_name": "音乐",
                "verbose_name_plural": "音乐",
                "db_table": "music",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(upload_to="avatars/", verbose_name="头像"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("intro", models.TextField(verbose_name="简介")),
                (
                    "resume",
                    models.TextField(
                        help_text='格式: [{"type":"education","content":"..."},{"type":"work","content":"..."}]',
                        verbose_name="简历(JSON格式)",
                    ),
                ),
                (
                    "contact",
                    models.TextField(
                        help_text='格式: [{"type":"email","icon":"fa-envelope","url":"mailto:xxx","text":"xxx"}]',
                        verbose_name="联系方式(JSON格式)",
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "个人信息",
                "verbose_name_plural": "个人信息",
                "db_table": "user_info",
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "cover_image",
                    models.ImageField(upload_to="works/", verbose_name="封面图"),
                ),
                ("desc", models.TextField(verbose_name="描述")),
                ("link", models.URLField(blank=True, verbose_name="链接")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "作品",
                "verbose_name_plural": "作品",
                "db_table": "works",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="AnimeScreenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="anime/screenshots/", verbose_name="截图"
                    ),
                ),
                (
                    "desc",
                    models.CharField(blank=True, max_length=200, verbose_name="描述"),
                ),
                (
                    "anime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="api.anime",
                        verbose_name="所属动漫",
                    ),
                ),
            ],
            options={
                "verbose_name": "动漫截图",
                "verbose_name_plural": "动漫截图",
                "db_table": "anime_screenshots",
            },
        ),
        migrations.CreateModel(
            name="GameScreenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="games/screenshots/", verbose_name="截图"
                    ),
                ),
                (
                    "desc",
                    models.CharField(blank=True, max_length=200, verbose_name="描述"),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="api.game",
                        verbose_name="所属游戏",
                    ),
                ),
            ],
            options={
                "verbose_name": "游戏截图",
                "verbose_name_plural": "游戏截图",
                "db_table": "game_screenshots",
            },
        ),
    ]
